learning_log/learning_log/learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('learning_logs.urls', namespace = 'learning_logs')),
]

learning_log/learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url

from . import views

urlpatterns = [
    #home page below
    url(r'^$', views.index, name = "index"),
    #Show all Topics
    url(r'^topics/$', views.topics, name = "topics"),

    url(r'^topic/(?P<topic_id>\d+)/$', views.topic, name = "topic"),
    #page for adding new topic 
    url(r'^new_topic/$', views.new_topic, name = "new_topic"),
    #page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name = "new_entry")
    #page for editing an entry 
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name = 'edit_entry'),

]
.

learning_log/learning_log/learning_logs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text= models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        """return a string representation of the model"""
        return self.text
        return self.date_added

class Entry(models.Model):
    """something specific learned about a topic"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):

        """Return a string rpresentation of the model"""
        if len(self.text) >= 50:
            return self.text[:100] + "... continued"
        
        else:
            return self.text



learning_log/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {'text':""}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {'text':""}
        widgets = {"text": forms.Textarea(attrs={'cols':40})}

learning_log/learning_log/learning_logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Topic, Entry
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """The Homepage for the the learning log """
    return render(request, "learning_logs/index.html")

def topics(request):
    """The page to display topics """
    topics = Topic.objects.order_by("date_added")
    context = {"topics":topics}
    return render(request, "learning_logs/topics.html", context)

def topic(request, topic_id):
    """"This page defines a view to access a topic by ID#"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic":topic, "entries":entries}
    return render(request, "learning_logs/topic.html", context)

def new_topic(request):
    """add a new topic"""
    if request.method != "Post":
        #no data submitted; create a blank form
        form = TopicForm()
    else:
        #POST data submitted; process data.
        form = TopicForm(data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("learning_logs:topics"))

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)

def new_entry(request, topic_id):
    """add a new entry"""
    if request.method != "Post":
        #no data submitted; create a blank form
        form = EntryForm()
    else:
        #POST data submitted; process data.
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse("learning_logs:topic", args = [topic_id]))


    context = {"topic":topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)

def edit_entry(request, entry_id):
    """Edit and existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != "POST":
        #initial request; pre fill form with current entry.
        form = EntryForm(instance = entry)
    else:
        # POST data submitted; process data
        form  = EntryForm(instance = entry , data = request.POST)
        if form.is_valid():
             form.save()
             return HttpResponseRedirect(reverse("learning_logs:topic", args = [topic.id]))

    context = {"entry":entry, "topic":topic, "form":form}
    return render (request, "learning_logs/edit_entry.html", context)



learning_log/learning_log/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Learnign Log Base </title>
</head>
<body>
        <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Dave's Cool Navbar</a>
                  </div>
              
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="{% url 'learning_logs:index' %}">Home<span class="sr-only">(current)</span></a></li>
                      <li><a href="{% url 'learning_logs:topics' %}">Topics </a></li>
                      <li><a href="{% url 'learning_logs:new_topic' %}">Add New Topic  </a></li>
                      </li>
                    </ul>
                    <form class="navbar-form navbar-left">
                      <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                      </div>
                      <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
              </nav>
          
            {% block content %} {% endblock content %} 
            <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>  




learning_log/learning_log/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome the Learning Logs</title>
</head>
<body>

    {% extends "learning_logs/base.html" %}
    {% block content %}
    <h2>Welcome to Learning Logs!</h2>
    <p>Learning log helps you keep track of your learning, for any topic your learning about.</p>
    {% endblock content %}

</body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New Entry</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
        
        {% block content %}
            
    <p><a href="{% url "learning_logs:topic" topic.id %}">{{ topic }}</a></p>
    <p>Add New Entry:</p>
        <form action="{% url "learning_logs:new_topic" %}" method ="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button name = "submit">add entry</button>

        </form>
        {% endblock content %}
</body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New topic</title>
</head>
<body>
        {% extends "learning_logs/base.html" %}
        
        {% block content %}
            
            <p>Add new topic:</p>
        <form action="{% url 'learning_logs:new_topic' %}" method ='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name = "submit">Add topic</button>

        </form>
        {% endblock content %}
</body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        {% extends "learning_logs/base.html" %}
        
                {% block content %}
    <div class = "Topic">
        
    <h3>Topic: <h4 style="color :blue";>{{ topic }}</h4> </h3>
    <p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id  %}">add new entry</a>
    </p>
    <ul>
        {% for entry in entries  %}
        <li>
            <p>{{entry.date_added|date:'M d, y h:i'}}</p>
            <p>{{entry.text|linebreaks }}</p>
        </li>
        {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
        {% endfor %}
    </ul>
    {% endblock content %}
    </div>
</body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        {% extends "learning_logs/base.html" %}

        {% block content %}
        <h2>
            Welcome to the Topics Page
        </h2>
        <h2>Topics:</h2>

        <ul>
            {% for topic in topics %}
                <li>
                   <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> 
                </li>
                {% empty %}
                <li>No Topics Have been added yet</li>
                {% endfor %}
        </ul>
        <a href="{% url 'learning_logs:new_topic' %}">Add new Topic </a> 
        {% endblock content %}
</body>
</html>